prometheus_domain_name: "prometheus.localhost"
alertmanager_domain_name: "alertmanager.localhost"
grafana_domain_name: "grafana.localhost"
role: prometheus

default_ec2_region: eu-west-1

# FIXME do we want to setup postfix ? Require SES login
# Postfix unused for now

#postfix_aliases:
#  - "root: admin@cycloid.io"
#  - "admin: admin@cycloid.io"
#  - "{{customer}}: root"

# postfix_basehostname: "{{ customer }}.cycloid.io"
# sasl_passwd:
#     username: "sesACCESSKEY"
#     password: !vault |
#           $ANSIBLE_VAULT;1.1;AES256
#           65636162663731373263353765353762363430633065306635623933303163363536353365353230
#           3966343664626230663038613937316563633835636264630a613435336364656433613535666565
#           66386138376635613839323862326438313031396635383535656230316333326630313166663438
#           3536326438636666360a643438306235356535666131633238366533383364366533356665373231
#           6361

#
# Nginx
#

# Use ssl on prometheus stack
prometheus_ssl: false

prometheus_certificat_name: prometheus.crt
prometheus_certificat_key_name: prometheus.key
alertmanager_certificat_name: "{{ prometheus_certificat_name }}"
alertmanager_certificat_key_name: "{{ prometheus_certificat_key_name }}"
grafana_certificat_name: "{{ prometheus_certificat_name }}"
grafana_certificat_key_name: "{{ prometheus_certificat_key_name }}"

certificats_src: "{{ playbook_dir }}/files/nginx/ssl/*"
certificats_dest: "/etc/nginx/ssl/"


nginx_auth_basic_files:
  # Default : prometheus / prometheus -> prometheus:$apr1$V0rOBZTd$xErJ7mzWne9Dx3mFtUIUl0
  prometheus:
    - "prometheus:$apr1$V0rOBZTd$xErJ7mzWne9Dx3mFtUIUl0"
  # Default : alertmanager / alertmanager -> alertmanager:$apr1$R6kEJoh9$1LZmJt8T3nGb9JUufeq/d/
  alertmanager:
    - "alertmanager:$apr1$R6kEJoh9$1LZmJt8T3nGb9JUufeq/d/"
#   # Default : grafana / grafana -> grafana:$apr1$YSYnc168$x7l8B0.I8e0usgr5ydU.5.
#   grafana:
#     - "grafana:$apr1$YSYnc168$x7l8B0.I8e0usgr5ydU.5."
# #  # Default : grafana / grafana -> grafana:$apr1$YSYnc168$x7l8B0.I8e0usgr5ydU.5.
# #  grafana:
# #    - "grafana:$apr1$YSYnc168$x7l8B0.I8e0usgr5ydU.5."

nginx_configs:
  proxy:
    - proxy_set_header X-Real-IP  $remote_addr
    - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
  gzip:
    - gzip on
    - gzip_disable msie6
  aws:
    - real_ip_header X-Forwarded-For
    - set_real_ip_from 0.0.0.0/0
  global:
    - client_max_body_size 5m

nginx_remove_sites:
  - default

nginx_sites_default:
  00-status:
    - listen 80
    - server_name 127.0.0.1
    - location / {
       deny all;
      }
    - location /nginx_status {
        stub_status on;
        access_log   off;
        allow 127.0.0.1;
        deny all;
      }

  07-grafana-80:
    - listen 80 default_server
    - server_name {{grafana_domain_name}}
    # - auth_basic            "Restricted"
    # - auth_basic_user_file  auth_basic/grafana
    - location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header   X-FORWARDED_PROTO http;
        proxy_set_header   X-FORWARDED_PORT 80;
      }
  08-prometheus-80:
    - listen 80
    - server_name {{prometheus_domain_name}}
    - auth_basic            "Restricted"
    - auth_basic_user_file  auth_basic/prometheus
    - location / {
        proxy_pass http://127.0.0.1:9090;
        proxy_set_header   X-FORWARDED_PROTO http;
        proxy_set_header   X-FORWARDED_PORT 80;
      }
  09-alertmanager-80:
    - listen 80
    - server_name {{alertmanager_domain_name}}
    - auth_basic            "Restricted"
    - auth_basic_user_file  auth_basic/alertmanager
    - location / {
        proxy_pass http://127.0.0.1:9093;
        proxy_set_header   X-FORWARDED_PROTO http;
        proxy_set_header   X-FORWARDED_PORT 80;
      }



nginx_sites_default_https:
  00-status:
    - listen 80
    - server_name 127.0.0.1
    - location / {
       deny all;
      }
    - location /nginx_status {
        stub_status on;
        access_log   off;
        allow 127.0.0.1;
        deny all;
      }

  07-grafana-443:
    - listen 443 ssl
    - server_name {{grafana_domain_name}}
    - ssl_certificate  {{ certificats_dest }}/{{ grafana_certificat_name }}
    - ssl_certificate_key {{ certificats_dest }}/{{ grafana_certificat_key_name }}

    # - auth_basic            "Restricted"
    # - auth_basic_user_file  auth_basic/grafana
    - location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header   X-FORWARDED_PROTO http;
        proxy_set_header   X-FORWARDED_PORT 80;
      }

  10-force-https:
     - listen 80 default_server
     - return 301 https://$server_name$request_uri
  12-prometheus-443:
     - listen 443 ssl default_server
     - server_name {{prometheus_domain_name}}
     - ssl_certificate  {{ certificats_dest }}/{{ prometheus_certificat_name }}
     - ssl_certificate_key {{ certificats_dest }}/{{ prometheus_certificat_key_name }}
     - auth_basic            "Restricted"
     - auth_basic_user_file  auth_basic/prometheus
     - location / {
         proxy_pass http://127.0.0.1:9090;
         proxy_set_header   X-FORWARDED_PROTO https;
         proxy_set_header   X-FORWARDED_PORT 443;
       }
  13-alertmanager-443:
     - listen 443 ssl
     - server_name {{alertmanager_domain_name}}
     - ssl_certificate  {{ certificats_dest }}/{{ alertmanager_certificat_name }}
     - ssl_certificate_key {{ certificats_dest }}/{{ alertmanager_certificat_key_name }}
     - auth_basic            "Restricted"
     - auth_basic_user_file  auth_basic/alertmanager
     - location / {
         proxy_pass http://127.0.0.1:9093;
         proxy_set_header   X-FORWARDED_PROTO https;
         proxy_set_header   X-FORWARDED_PORT 443;
       }


nginx_sites: "{% if not prometheus_ssl %}{{ nginx_sites_default }}{% else %}{{ nginx_sites_default_https }}{% endif %}"


#
# Alertmanager
#

install_alertmanager: true
alertmanager_hostname: "{{ alertmanager_domain_name }}"

smtp_smarthost: 'smtp.gmail.com:587'
smtp_from: 'foo@bar.com'
smtp_auth_username: 'foo@bar.com'
smtp_auth_password: 'barfoo'
send_alert_to: 'foo@bar.com'

alertmanager_global:
  # ResolveTimeout is the time after which an alert is declared resolved
  # if it has not been updated.
  resolve_timeout: 15m

  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: "{{ smtp_smarthost }}"
  smtp_from: "{{ smtp_from }}"
  smtp_auth_username: "{{ smtp_auth_username }}"
  smtp_auth_password: "{{ smtp_auth_password }}"

alertmanager_route:
  group_by:
    - customer
    - project
    - env
    - alertname
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 15m
  receiver: default
  routes:
  - match:
      receiver: email
      severity: critical
    receiver: default

alertmanager_receivers:
  - name: 'default'
    email_configs:
    - to: "{{ send_alert_to }}"

alertmanager_inhibit_rules:
- source_match:
    severity: critical
  target_match:
    severity: warning
  equal:
  - instance
  - customer
  - project
  - env
  - alertname

#
# Prometheus
#

install_prometheus: true
prometheus_hostname: "{{ prometheus_domain_name }}"
prometheus_data_retention: 60d

# Override to keep less longer datas default 15d
prometheus_commandline_args:
  config.file: "/prometheus-data/prometheus.yml"
  storage.tsdb.path: "/prometheus-data/data"
  storage.tsdb.retention: "{{ prometheus_data_retention }}"

prometheus_scrape_interval: 1m
prometheus_evaluation_interval: 1m

default_alert_rules: false
prometheus_rule_files:
  - templates/telegraf.rules
  #- '*.rules'
  # Provide my own local rules
  #- '{{playbook_dir}}/templates/*.rules'

# Example of alertmanager override config
# prometheus_alerting:
#   alertmanagers:
#   - scheme: https
#     basic_auth:
#       username: cycloid
#       password: "{{vault_alertmanager_password}}"
#     static_configs:
#     - targets:
#       - "myalertmanager.com"

prometheus_scrape_configs_telegraph:
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['{{ ansible_default_ipv4.address }}:9093']
    metric_relabel_configs:
    # Not store unwanted metrics
    - source_labels: [__name__]
      action: drop
      regex: go_(.*)

    # Force labels on metrics
    # Instance label : Public IP, if not, default private IP
    - source_labels: [__address__]
      action: replace
      target_label: instance


prometheus_scrape_configs_global:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          Name: "prometheus"
          project: "{{ project }}"
          env: "{{ env }}"
          role: "{{ role }}"
          client: "{{ customer }}"
          customer: "{{ customer }}"
    metric_relabel_configs:
    # Not store unwanted metrics
    - source_labels: [__name__]
      action: drop
      regex: go_(.*)

  - job_name: 'telegraf via EC2 service discovery'
    scheme: http
    ec2_sd_configs:
    - region: "{{ec2_region | default(default_ec2_region) }}"
      # Need https://www.robustperception.io/automatically-monitoring-ec2-instances/
      # Using role or accesskey
      #access_key: "{{access_key}}"
      #secret_key: "{{secret_key}}"
      port: 9100

    relabel_configs:
    # Filer instance by labels whitelist
    #- source_labels: [__meta_ec2_tag_client, __meta_ec2_tag_project, __meta_ec2_tag_env, __meta_ec2_tag_role]
    #  action: keep
    #  regex: cycloid;demo;preprod;front

    # Filter of instances blacklist
    # - source_labels: [__meta_ec2_tag_client, __meta_ec2_tag_project]
    #   action: drop
    #   regex: cycloid;kubernetes

    - source_labels: [__meta_ec2_tag_monitoring_discovery]
      action: drop
      regex: false

    - source_labels: [__name__]
      action: drop
      regex: go_(.*)

    - source_labels: [__meta_ec2_private_ip]
      regex: '^(.+)$'
      replacement: '${1}:9100'
      target_label: __address__
    # Relabel target with public IP if there is one
    # Use this rule in case you want prometheus to prefer query telegraf exporter on the public IP
    #- source_labels: [__meta_ec2_public_ip]
    #  regex: '^(.+)$'
    #  replacement: '${1}:9100'
    #  target_label: __address__

    # Force labels on metrics
    # Instance label : Public IP, if not, default private IP
    - source_labels: [__meta_ec2_private_ip]
      action: replace
      target_label: instance
    - source_labels: [__meta_ec2_public_ip]
      regex: '^(.+)$'
      replacement: '${1}'
      target_label: instance
    # In case you prefer instance id
    #- source_labels: [__meta_ec2_instance_id]
    #  target_label: instance

    # Get some ec2 labels
    - source_labels: [__meta_ec2_tag_Name]
      target_label: Name
    - source_labels: [__meta_ec2_tag_project]
      target_label: project
    - source_labels: [__meta_ec2_tag_env]
      target_label: env
    - source_labels: [__meta_ec2_tag_role]
      target_label: role
    - source_labels: [__meta_ec2_tag_client]
      target_label: client
    - source_labels: [__meta_ec2_tag_customer]
      target_label: customer
    - source_labels: [__meta_ec2_availability_zone]
      target_label: availability_zone


# merge alertmanager if needed
prometheus_scrape_configs: "{% if install_alertmanager == 'true' %}{{ prometheus_scrape_configs_global + prometheus_scrape_configs_telegraph }}{% else %}{{ prometheus_scrape_configs_global }}{% endif %}"


#
# Telegraf
#

# See telegraf inputs for more plugings https://github.com/influxdata/telegraf/tree/master/plugins/inputs
# Like https://github.com/influxdata/telegraf/tree/master/plugins/inputs/net_response for tcp port checks
telegraf_plugins_extra:
  linux_sysctl_fs:
  conntrack:
  nginx:
    config:
        - urls = ["http://127.0.0.1/nginx_status"]
  check-lb-certs:
    plugin: exec
    config:
        - commands = ["/usr/bin/check_lb_certs.py"]
        - data_format = "influx"
        - interval = "30m"
  check-ses:
    plugin: exec
    config:
        - commands = ["/usr/bin/check_ses.py"]
        - data_format = "influx"
        - interval = "10m"
  check-instance-events:
    plugin: exec
    config:
        - commands = ["/usr/bin/check_instance_events.py"]
        - data_format = "influx"
        - interval = "10m"
  check-rds-events:
    plugin: exec
    config:
        - commands = ["/usr/bin/check_rds_events.py"]
        - data_format = "influx"
        - interval = "10m"
  # https://github.com/influxdata/telegraf/tree/master/plugins/inputs/cloudwatch
  cloudwatch_ec2:
    plugin: cloudwatch
    config:
        - 'region = "{{ec2_region | default(default_ec2_region) }}"'
        - period = "10m"
        - interval = "10m"
        - namespace = "AWS/EC2"
        - "[[inputs.cloudwatch.metrics]]"
        -   names = ["CPUCreditBalance"]
        - ## Dimension filters for Metric (optional)
        -  "[[inputs.cloudwatch.metrics.dimensions]]"
        -   name = "InstanceId"
        -   value = "*"
  cloudwatch_rds:
    plugin: cloudwatch
    config:
        - 'region = "{{ec2_region | default(default_ec2_region) }}"'
        - period = "10m"
        - interval = "10m"
        - namespace = "AWS/RDS"
        - "[[inputs.cloudwatch.metrics]]"
        -   names = ["CPUCreditBalance"]
        - ## Dimension filters for Metric (optional)
        -  "[[inputs.cloudwatch.metrics.dimensions]]"
        -   name = "DBInstanceIdentifier"
        -   value = "*"


#
# grafana
#
install_grafana: true
grafana_database_host: "{{ rds_address | default('localhost') }}:3306"
grafana_database_name: "{{ rds_database | default('grafana') }}"
grafana_database_user: "{{ rds_username | default('grafana') }}"
grafana_database_password: "{{ rds_password | default('s3cr3t') }}"
grafana_database_type: "{{ rds_engine | default('sqlite3') }}"

grafana_dashboards_files:
  - '{{playbook_dir}}/files/dashboards/*.json'
