---

#
# Prometheus
#
- hosts: tag_role_prometheus:&tag_project_{{project}}:&tag_cycloid_io_true:&tag_env_{{ env }}
  become: yes
  serial: 50%

  vars_files:
    - "environments/default_prometheus.yml"
    - "environments/{{env}}-prometheus.yml"
  pre_tasks:

    - name: "Create ssl directory"
      file:
        path: "{{ certificats_dest }}"
        state: directory
      when: prometheus_ssl | bool

    - name: "Install ssl certificat"
      copy:
        src: "{{ item }}"
        dest: "{{ certificats_dest }}"
        mode: 0600
      with_fileglob:
        - "{{ certificats_src }}"
      when: prometheus_ssl | bool




  roles:
    # Install prometheus
    - {role: geerlingguy.docker, tags: docker}
    - {role: cycloid.prometheus, path: /opt/prometheus, tags: prometheus}
    # Monitoring client part
    - {role: cycloid.telegraf, tags: telegraf}
    - {role: jdauphant.nginx, tags: nginx}

